name: HIL Build
on:
  workflow_run:
    workflows: ["OBC Build"]
    types:
      - completed

concurrency:
  group: rm46-hil
  cancel-in-progress: false

jobs:
  build-linux:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, hil, rm46]

    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        sudo apt install -y build-essential gcc-multilib g++-multilib cmake curl
        python3 -m venv venv/
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .

    - name: Create Ground Station Binary Directory
      run: |
        mkdir build_gs
        cd build_gs
        cmake .. -DCMAKE_BUILD_TYPE=GS

    - name: Build
      run: |
        cd build_gs
        cmake --build .

    - name: Download binary with CRC
      uses: actions/download-artifact@v4
      with:
        name: launchpad-bin
        path: .

    - name: Run HIL
      run: |
          source venv/bin/activate
          python3 hil/hil_main.py /dev/ttyACM0 OBC-firmware-crc.bin
